# Project settings
name: 'odion_data_platform'
version: '1.0.0'
profile: 'odion_data_platform'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# directories to be removed by `dbt clean`
clean-targets:
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models
models:
  odion_data_platform:
    staging:
      +materialized: view
      +schema: staging

    intermediate:
      +materialized: view
      +schema: intermediate

    marts:
      +materialized: view
      +schema: marts

      # dimensions:
      #  +schema: dimensions
      
      # facts:
      #   +schema: facts
      
      # reports:
      #   +schema: reports

vars:
  dbt_date:
    calendar:
      default_last_day: '2040-12-31'
    time_zone: Europe/Amsterdam
    first_day_of_week: 1


