{% macro get_locatiecluster(locatienaam, niveau2, niveau3) %}
    case
        when lower(isnull({{ locatienaam }}, '')) like '%externe aanbieder%'
          or isnull({{ niveau2 }}, '') like '%Externe aanbieder%'
          then N'Externe aanbieder'
        when isnull({{ niveau2 }}, '') like '%Aanmeldingen%'
          then N'Aanmeldingen'
        when lower(isnull({{ locatienaam }}, '')) like '%wachtl%'
          or isnull({{ niveau2 }}, '') like '%Wachtlijst%'
          then N'Wachtlijsten'
        when isnull({{ niveau2 }}, '') like '%Archief%'
          then N'Archief'
        when isnull({{ niveau2 }}, '') like '%Overige%'
          then N'Overige'
        when lower(isnull({{ locatienaam }}, '')) like '%in de wijk%'
          or isnull({{ niveau3 }}, '') like '%Ambulant%'
          then N'Ambulant'
        when lower(isnull({{ locatienaam }}, '')) like '%dagbesteding%'
          or isnull({{ niveau3 }}, '') like '%Dagbesteding%'
          then N'Dagbesteding'
        when lower(isnull({{ locatienaam }}, '')) like '%logeren%'
          or isnull({{ niveau3 }}, '') like '%Logeren%'
          then N'Logeren'
        when isnull({{ niveau3 }}, '') like '%Wonen%'
          then N'Wonen'
        when isnull({{ niveau3 }}, '') like '%Behandeling%'
          then N'Behandeling'
        when isnull({{ niveau3 }}, '') like '%Kind en gezin%'
          then N'Kind en gezin'
        when isnull({{ niveau3 }}, '') like '%Multidisciplinair Team%'
          then N'Multidisciplinair Team'
        else N'Overige'
    end
{% endmacro %}
